import { Project, Column, Table } from '../types';

function getColumnDefinition(col: Column): string {
  let def = `  [${col.name}] ${col.type}`;

  if (col.length) {
    def += `(${col.length})`;
  } else if (col.precision !== null && col.scale !== null) {
    def += `(${col.precision},${col.scale})`;
  }

  if (col.isAutoIncrement) def += ' IDENTITY(1,1)';

  if (col.isNotNull) def += ' NOT NULL';
  if (col.isUnique && !col.isPrimaryKey) def += ' UNIQUE';

  if (col.defaultValue !== null && col.defaultValue !== undefined) {
    def += ` DEFAULT ${col.defaultValue}`;
  }

  return def;
}

export function generateMSSQL(project: Project): string {
  let sql = `-- Generated by SchemaVision\n-- Dialect: SQL Server\n\n`;

  project.tables.forEach(table => {
    sql += `CREATE TABLE [${table.name}] (\n`;

    const defs: string[] = table.columns.map(getColumnDefinition);

    // Primary Keys
    const pkCols = table.columns.filter(c => c.isPrimaryKey);
    if (pkCols.length > 0) {
      defs.push(`  PRIMARY KEY ([${pkCols.map(c => c.name).join('], [')}])`);
    }

    sql += defs.join(',\n');
    sql += `\n);\nGO\n\n`;

    // Comments (Extended Properties)
    if (table.comment) {
      sql += `EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'${table.comment.replace(/'/g, "''")}', @level0type = N'Schema', @level0name = 'dbo', @level1type = N'Table', @level1name = '${table.name}';\nGO\n`;
    }

    table.columns.forEach(col => {
      if (col.comment) {
        sql += `EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'${col.comment.replace(/'/g, "''")}', @level0type = N'Schema', @level0name = 'dbo', @level1type = N'Table', @level1name = '${table.name}', @level2type = N'Column', @level2name = '${col.name}';\nGO\n`;
      }
    });

    // Indexes
    table.columns.forEach(col => {
      if (col.isIndexed && !col.isPrimaryKey && !col.isUnique) {
        sql += `CREATE INDEX [idx_${table.name}_${col.name}] ON [${table.name}] ([${col.name}]);\nGO\n`;
      }
    });
    sql += '\n';
  });

  // Foreign Keys
  if (project.relationships.length > 0) {
    sql += `-- Foreign Keys\n`;
    project.relationships.forEach(rel => {
      const sourceTable = project.tables.find(t => t.id === rel.sourceTableId);
      const targetTable = project.tables.find(t => t.id === rel.targetTableId);

      if (!sourceTable || !targetTable) return;

      const sourceCol = sourceTable.columns.find(c => c.id === rel.sourceColumnId);
      const targetCol = targetTable.columns.find(c => c.id === rel.targetColumnId);

      if (!sourceCol || !targetCol) return;

      sql += `ALTER TABLE [${targetTable.name}] ADD CONSTRAINT [fk_${targetTable.name}_${targetCol.name}] FOREIGN KEY ([${targetCol.name}]) REFERENCES [${sourceTable.name}] ([${sourceCol.name}]);\nGO\n`;
    });
  }

  return sql;
}
