import { Project, Column, Table } from '../types';

function getColumnDefinition(col: Column): string {
  let def = `  \`${col.name}\` ${col.type}`;

  if (col.length) {
    def += `(${col.length})`;
  } else if (col.precision !== null && col.scale !== null) {
    def += `(${col.precision},${col.scale})`;
  }

  if (col.isNotNull) def += ' NOT NULL';
  if (col.isAutoIncrement) def += ' AUTO_INCREMENT';
  if (col.isUnique && !col.isPrimaryKey) def += ' UNIQUE';

  if (col.defaultValue !== null && col.defaultValue !== undefined) {
    def += ` DEFAULT ${col.defaultValue}`;
  }

  if (col.comment) {
    def += ` COMMENT '${col.comment.replace(/'/g, "\\'")}'`;
  }

  return def;
}

export function generateMySQL(project: Project): string {
  let sql = `-- Generated by SchemaVision\n-- Dialect: MySQL\n\n`;

  project.tables.forEach(table => {
    sql += `CREATE TABLE \`${table.name}\` (\n`;

    const defs: string[] = table.columns.map(getColumnDefinition);

    // Primary Keys
    const pkCols = table.columns.filter(c => c.isPrimaryKey);
    if (pkCols.length > 0) {
      defs.push(`  PRIMARY KEY (\`${pkCols.map(c => c.name).join('`, `')}\`)`);
    }

    // Indexes
    table.columns.forEach(col => {
      if (col.isIndexed && !col.isPrimaryKey && !col.isUnique) {
         defs.push(`  INDEX \`idx_${col.name}\` (\`${col.name}\`)`);
      }
    });

    sql += defs.join(',\n');
    sql += `\n)`;

    if (table.comment) {
      sql += ` COMMENT='${table.comment.replace(/'/g, "\\'")}'`;
    }

    sql += `;\n\n`;
  });

  // Foreign Keys
  if (project.relationships.length > 0) {
    sql += `-- Foreign Keys\n`;
    project.relationships.forEach(rel => {
      const sourceTable = project.tables.find(t => t.id === rel.sourceTableId);
      const targetTable = project.tables.find(t => t.id === rel.targetTableId);

      if (!sourceTable || !targetTable) return;

      const sourceCol = sourceTable.columns.find(c => c.id === rel.sourceColumnId);
      const targetCol = targetTable.columns.find(c => c.id === rel.targetColumnId);

      if (!sourceCol || !targetCol) return;

      sql += `ALTER TABLE \`${targetTable.name}\` ADD CONSTRAINT \`fk_${targetTable.name}_${targetCol.name}\` FOREIGN KEY (\`${targetCol.name}\`) REFERENCES \`${sourceTable.name}\` (\`${sourceCol.name}\`);\n`;
    });
  }

  return sql;
}
