import { Project, Column, Table } from '../types';

function getColumnDefinition(col: Column): string {
  let def = `  "${col.name}" ${col.type}`;

  if (col.length) {
    def += `(${col.length})`;
  } else if (col.precision !== null && col.scale !== null) {
    def += `(${col.precision},${col.scale})`;
  }

  if (col.isAutoIncrement) {
    // In PostgreSQL, typically handled via SERIAL or generated identity
    // For pure DDL, mapping common integer types to serial equivalents is standard
    if (col.type === 'INT') def = `  "${col.name}" SERIAL`;
    else if (col.type === 'BIGINT') def = `  "${col.name}" BIGSERIAL`;
    else if (col.type === 'SMALLINT') def = `  "${col.name}" SMALLSERIAL`;
  }

  if (col.isPrimaryKey) def += ' PRIMARY KEY';
  else if (col.isUnique) def += ' UNIQUE';

  if (col.isNotNull && !col.isPrimaryKey) def += ' NOT NULL';

  if (col.defaultValue) {
    // If it's a string/varchar, we might need quotes, but let's assume raw SQL for now
    def += ` DEFAULT ${col.defaultValue}`;
  }

  return def;
}

export function generatePostgreSQL(project: Project): string {
  let sql = `-- Generated by SchemaVision\n-- Dialect: PostgreSQL\n\n`;

  // Tables
  project.tables.forEach(table => {
    if (table.comment) {
      sql += `/*\n * ${table.comment}\n */\n`;
    }
    sql += `CREATE TABLE "${table.name}" (\n`;

    const colDefs = table.columns.map(getColumnDefinition);
    sql += colDefs.join(',\n');
    sql += `\n);\n\n`;

    // Column Comments
    table.columns.forEach(col => {
      if (col.comment) {
        sql += `COMMENT ON COLUMN "${table.name}"."${col.name}" IS '${col.comment.replace(/'/g, "''")}';\n`;
      }
    });
    if (table.columns.some(c => c.comment)) sql += '\n';

    // Indexes
    table.columns.forEach(col => {
      if (col.isIndexed && !col.isPrimaryKey && !col.isUnique) {
        sql += `CREATE INDEX "idx_${table.name}_${col.name}" ON "${table.name}" ("${col.name}");\n`;
      }
    });
  });

  // Relationships (Foreign Keys)
  if (project.relationships.length > 0) {
    sql += `\n-- Foreign Keys\n`;
    project.relationships.forEach(rel => {
      const sourceTable = project.tables.find(t => t.id === rel.sourceTableId);
      const targetTable = project.tables.find(t => t.id === rel.targetTableId);

      if (!sourceTable || !targetTable) return;

      const sourceCol = sourceTable.columns.find(c => c.id === rel.sourceColumnId);
      const targetCol = targetTable.columns.find(c => c.id === rel.targetColumnId);

      if (!sourceCol || !targetCol) return;

      // In SchemaVision, connections go from Source to Target.
      // If 1:N, Target holds the FK referencing Source.
      sql += `ALTER TABLE "${targetTable.name}" ADD CONSTRAINT "fk_${targetTable.name}_${targetCol.name}" FOREIGN KEY ("${targetCol.name}") REFERENCES "${sourceTable.name}" ("${sourceCol.name}");\n`;
    });
  }

  return sql;
}
