import { Project, Column, Table } from '../types';

function getColumnDefinition(col: Column): string {
  let type: string = col.type;
  if (col.isAutoIncrement && col.isPrimaryKey) {
    type = 'INTEGER'; // SQLite requirement for AUTOINCREMENT
  }

  let def = `  "${col.name}" ${type}`;

  // SQLite ignores length/precision but it's standard DDL
  if (col.length) {
    def += `(${col.length})`;
  }

  if (col.isPrimaryKey) {
    def += ' PRIMARY KEY';
    if (col.isAutoIncrement) def += ' AUTOINCREMENT';
  }

  if (col.isNotNull && !col.isPrimaryKey) def += ' NOT NULL';
  if (col.isUnique && !col.isPrimaryKey) def += ' UNIQUE';

  if (col.defaultValue !== null && col.defaultValue !== undefined) {
    def += ` DEFAULT ${col.defaultValue}`;
  }

  return def;
}

export function generateSQLite(project: Project): string {
  let sql = `-- Generated by SchemaVision\n-- Dialect: SQLite\n\n`;

  project.tables.forEach(table => {
    if (table.comment) {
      sql += `/* ${table.comment} */\n`;
    }

    sql += `CREATE TABLE "${table.name}" (\n`;

    const defs: string[] = table.columns.map(getColumnDefinition);

    // Foreign Keys inline for SQLite
    const tableRels = project.relationships.filter(r => r.targetTableId === table.id);
    tableRels.forEach(rel => {
      const sourceTable = project.tables.find(t => t.id === rel.sourceTableId);
      const sourceCol = sourceTable?.columns.find(c => c.id === rel.sourceColumnId);
      const targetCol = table.columns.find(c => c.id === rel.targetColumnId);

      if (sourceTable && sourceCol && targetCol) {
        defs.push(`  FOREIGN KEY ("${targetCol.name}") REFERENCES "${sourceTable.name}" ("${sourceCol.name}")`);
      }
    });

    sql += defs.join(',\n');
    sql += `\n);\n\n`;

    // Indexes
    table.columns.forEach(col => {
      if (col.isIndexed && !col.isPrimaryKey && !col.isUnique) {
        sql += `CREATE INDEX "idx_${table.name}_${col.name}" ON "${table.name}" ("${col.name}");\n`;
      }
    });

    if (table.columns.some(c => c.isIndexed)) sql += '\n';
  });

  return sql;
}
